# SPDX-FileCopyrightText: 2025 Azokle Private Limited
# SPDX-License-Identifier: Apache-2.0

name: build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    name: Build Debug APK
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Build
        uses: ./.github/workflows/build
